#server:
#  port: 8090
#
#spring:
#  # ----------------------------------------
#  # A. H2 Database Configuration
#  # ----------------------------------------
#  datasource:
#    # Use the H2 in-memory database
#    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#
#  # ----------------------------------------
#  # B. JPA/Hibernate Configuration
#  # ----------------------------------------
#  jpa:
#    hibernate:
#      # Automatically create or update the schema based on your entities.
#      # Use 'update' to preserve data between restarts (if the DB remains in memory) or 'create-drop' for fresh starts.
#      ddl-auto: update
#    show-sql: true # Log all SQL statements to the console (useful for debugging)
#    properties:
#      hibernate:
#        # Format the SQL logs for readability
#        format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  # ----------------------------------------
#  # C. H2 Console Configuration (for viewing data)
#  # ----------------------------------------
#  h2:
#    console:
#      # Enable the H2 console
#      enabled: true
#      # Set the access path for the console (e.g., http://localhost:8080/h2-console)
#      path: /h2-console
#      # Allow remote access (use with caution in production)
#      settings:
#        web-allow-others: true